### ISSUE TITLE
[FEATURE REQUEST] Category Card Improvements

### ISSUE THREAD

**Issue by akemalakcay** [atolye15/checklist#110]
I have 2 suggestions regarding category cards:

1- There is min-height set on the category cards, but it creates an issue on the mobile screens where the min-height causes for the card to be too high. 

Solution here might be removing min-height on sm-down.

2- We should decrease padding-sides from 24px to 16px on md-down. It is already 16px on sm-down.

**Comment by ecempehlivan** [comment]
Sounds good. We need to take an action @hsnaydd @bugrakocak
