### ISSUE TITLE
[FEATURE REQUEST] Checklist Card Improvements

### ISSUE THREAD

**Issue by akemalakcay** [atolye15/checklist#111]
The paddings on checklist cards should be decreased on mobile devices. The current padding-sides is set to be 24px, would suit better if it'd be 16px on sm-down.

**Comment by ecempehlivan** [comment]
I think it is not so crucial. Now mobile-view has a really good feeling, even tablet-view has a fantastic feeling! :) IMHO we can skip that, but you're the designer. 🤷‍♀️

**Comment by bugrakocak** [comment]
@akemalakcay Are we sure about making pads 16px for only sm-down devices but not also md sizes ? If I am not mistaken we applied 16px side paddings in category cards for both sm and md devices.

**Comment by akemalakcay** [comment]
> I think it is not so crucial. Now mobile-view has a really good feeling, even tablet-view has a fantastic feeling! :) IMHO we can skip that, but you're the designer. 🤷‍♀️Let's vote!

It's not crucial but really important especially since we have changed the paddings on category cards, it differs highly and makes a bad look. @ecempehlivan 

> @akemalakcay Are we sure about making pads 16px for only sm-down devices but not also md sizes ? If I am not mistaken we applied 16px side paddings in category cards for both sm and md devices.

Yeah you're right it should be md down. @bugrakocak
