### ISSUE TITLE
[ACCEPTED] [FEATURE REQUEST] Reset Indicator

### ISSUE THREAD

**Issue by akemalakcay** [atolye15/checklist#116]
When a user clicks on the reset button on the checklist detail page the website just resets. And since the page animation doesn't activated it looks like a bug, so maybe we should make page it to have it's main page animation activated when the checklist is resetted.

**Comment by ecempehlivan** [comment]
Agree! Any volunteers or any disagree? @alpcanaydin @hsnaydd

**Comment by alpcanaydin** [comment]
I totally agree. We can add this feature.

**Comment by akemalakcay** [comment]
This issue is solved at #135
