### ISSUE TITLE
[ACCEPTED] [FEATURE REQUEST] Featured checklists

### ISSUE THREAD

**Issue by alpcanaydin** [atolye15/checklist#125]
We can add an optional frontmatter value like `featured: true` to boost some checklists on the home page. Therefore, the selected checklists can be on top of the checklists list. What do you think guys? @ecempehlivan @akemalakcay

**Comment by akemalakcay** [comment]
I love the idea, but if we are going to do that we should seperate the featured checklists from the rest. So maybe we can add a featured section?

**Comment by alpcanaydin** [comment]
> I love the idea, but if we are going to do that we should seperate the featured checklists from the rest. So maybe we can add a featured section?

It's possible but I thought like we can move them to top of the list at home page. If you want to work a design variation, of course, you can :)

**Comment by akemalakcay** [comment]
> > I love the idea, but if we are going to do that we should seperate the featured checklists from the rest. So maybe we can add a featured section?
> 
> It's possible but I thought like we can move them to top of the list at home page. If you want to work a design variation, of course, you can :)

Hold my beer 🍺
