### ISSUE TITLE
multiple check

### ISSUE THREAD

**Issue by ademilter** [atolye15/checklist#156]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open https://checklist.atolye15.com/checklist/a-remote-day-of-atolye15
2. checked "Wash your hands"
3. trigger check "Wash your hands" (This should be your at least 4th washing today.)

<img width="687" alt="Screen Shot 2020-03-23 at 16 56 59" src="https://user-images.githubusercontent.com/187922/77324993-9d18f780-6d28-11ea-8e29-58be2da30087.png">

**Comment by akemalakcay** [comment]
Checklist Author here ✋

I understand your confusion as it might cause to one. The intention was to remind everyone to wash their hands frequently in a jokey way. @ademilter Hope that clears it for you 😄

**Comment by akemalakcay** [comment]
> Checklist Author here ✋
> 
> I understand your confusion as it might cause to one. The intention was to remind everyone to wash their hands frequently in a jokey way. @ademilter Hope that clears it for you 😄

Oh wait... I just understood the issue here, we are on it right now! Nice catch 🤘

**Comment by akemalakcay** [comment]
issue fixed on #157
