### ISSUE TITLE
How To Run On My Server?

### ISSUE THREAD

**Issue by lahmacun** [atolye15/checklist#160]
First of all I really liked the project. Congratulations :clap: :clap: 
I'm not experienced with Gatsby. I was trying to run this project on my own server. I run `gatsby build` and upload the public folder to server but I'm not sure about is this the best way. I created a Gitlab CI file, I'm building project and sending files to server over FTP but it's taking at least 15 minutes. There must be a more reasonable way. Can you add documentation about the deploy?

**Comment by alpcanaydin** [comment]
Hey 👋

There is no specific deployment instructions actually, it depends on the tool you use. But, as you said you need to run `gatsby build` command to get compiled files. Before this, please do not forget to create `.env` file from `example.env` with your own values.
