### ISSUE TITLE
[FEATURE REQUEST] Author of the Checklist

### ISSUE THREAD

**Issue by akemalakcay** [atolye15/checklist#161]
This was been asked by couple people during the development process of the project and I wanted to bring this up to discussion.

Is it possible to add authors of the checklists to the checklist detail? Since the project is live and open for anyone's contribution now, I believe it would be encouraging and rewarding to show the author's name on the checklist, (maybe we could link it to their Github profile, idk). 

I am not sure if we could get the name (or maybe github username) of the author but I've just created an avatar set just in case we can add this feature.

Let's discuss this:

![avatars](https://user-images.githubusercontent.com/58132405/77822357-e3909c80-7102-11ea-9598-70574ee26176.png)
![detail-author-frontend](https://user-images.githubusercontent.com/58132405/77822249-fb1b5580-7101-11ea-868b-3ef9551dd7cc.png)

**Comment by alpcanaydin** [comment]
Since we don't have the authors of files we aren't able to do this feature yet. But if we find a way to do, then we'll develop this definitely.
