### ISSUE TITLE
[FEATURE REQUEST] Display categories on home page

### ISSUE THREAD

**Issue by bugrakocak** [atolye15/checklist#95]
When you land on the home page for the first time it is hard to detect categories rapidly.

I suggest that it would be better to have category cards above the tag list.

**Comment by ecempehlivan** [comment]
I think the main focus of the project should be the checklists instead of categories. Putting down the categories above the cards will decrease the ease of reaching the checklists.

**Comment by alpcanaydin** [comment]
I think we can close this issue since we won't implement this feature.
